# Embeds binary files (fonts, ...) into a generated C++ source as byte arrays, so the
# executable carries them and nothing has to be staged next to it at runtime.
#
# Usage:
#   alryn_embed_files(<out.cpp> <symbol> <file> [<symbol> <file> ...])
#
# For each pair it defines, in namespace alryn::embedded:
#   extern const unsigned char <symbol>[];
#   extern const std::size_t   <symbol>_size;
# Declare them yourself where they're used. The files are configure-time dependencies,
# so editing one re-runs CMake and regenerates the source.

function(alryn_embed_files out_cpp)
    set(args ${ARGN})
    list(LENGTH args n)
    math(EXPR odd "${n} % 2")
    if(n EQUAL 0 OR odd)
        message(FATAL_ERROR "alryn_embed_files: expected <symbol> <file> pairs")
    endif()

    set(body "// Generated by cmake/EmbedFiles.cmake - do not edit.\n#include <cstddef>\n\nnamespace alryn::embedded {\n")
    math(EXPR last "${n} - 1")
    foreach(i RANGE 0 ${last} 2)
        math(EXPR j "${i} + 1")
        list(GET args ${i} sym)
        list(GET args ${j} file)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${file})
        file(READ ${file} hex HEX)
        string(LENGTH "${hex}" hex_len)
        math(EXPR size "${hex_len} / 2")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
        # Wrap the array every 32 bytes so the generated file stays editor-friendly.
        string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")
        string(APPEND body "extern const unsigned char ${sym}[] = {\n${bytes}\n};\n")
        string(APPEND body "extern const std::size_t ${sym}_size = ${size};\n\n")
    endforeach()
    string(APPEND body "} // namespace alryn::embedded\n")

    # Only rewrite on change, so an unchanged re-configure doesn't force a rebuild.
    if(EXISTS ${out_cpp})
        file(READ ${out_cpp} old)
    endif()
    if(NOT "${old}" STREQUAL "${body}")
        file(WRITE ${out_cpp} "${body}")
    endif()
endfunction()
